version: "3"

volumes:
  storage:

services:
  # Main app.
  nvr:
    shm_size: 500m
    build:
      context: .
      dockerfile: ./Dockerfile-cuda
    container_name: nvr_app
    ports:
      - 2020:2020 # App is hosted on port 2020
#      - 2021:2021 # RTSP port
#      - 2022:2022 # HLS port
      - 12000:22 # ssh
    privileged: true
    environment:
      - TZ=Asia/Seoul # Timezone.
    volumes:
      - ./configs:/home/_nvr/os-nvr/configs # Configs.
      - ./storage:/home/_nvr/os-nvr/storage # Storage.
      - /home/_nvr/os-nvr/.cache # Unnamed cache volume.
      - /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu, utility, compute, video]

  # Web server.
  caddy:
    image: caddy:2.6.2-alpine
    container_name: nvr_caddy
    ports:
      - 8004:80 # Only used to redirect to https_port
      - 8005:443 # Needs to match https_port in ./configs/Caddyfile
    volumes:
      - /data
      - ./configs/Caddyfile.conf:/etc/caddy/Caddyfile
    environment:
        TZ: "Asia/Seoul"